/*
 *  This is the entry point React/JS file for the Correlation Nation app.
 *  It was auto-generated by create-react-app.
 */
import React from "react";
import { render } from "react-dom";
import "./custom.scss";
//import "bootstrap/dist/css/bootstrap.min.css";
import App from "./app/containers/app";

render(<App />, document.getElementById("root"));
